### ISSUE TITLE
v2.4- Maven dependency is considered to be a newer version than v3-

### ISSUE THREAD

**Issue by camsaul** [liquidz/antq#100]
I'm using `v3-rev20180622-1.27.0`, and antq is suggesting I upgrade to `v2.4-rev20180622-1.30.8`:

```
|    :file |                                         :name |              :current |                 :latest |
|----------+-----------------------------------------------+-----------------------+-------------------------|
| deps.edn | com.google.apis/google-api-services-analytics | v3-rev20180622-1.27.0 | v2.4-rev20180622-1.30.8 |
```

It's actually an older version of the API so "upgrading" to that would end up breaking my project. Shouldn't `3` be considered newer than `2.4`?

**Comment by liquidz** [comment]
@camsaul Thanks for your reporting!
It seems a problem in [xsc/version-clj](https://github.com/xsc/version-clj).

I'll have a look and report to version-clj.

**Comment by liquidz** [comment]
c.f. https://github.com/xsc/version-clj/pull/18

**Comment by liquidz** [comment]
@camsaul I've cut a new release.
Could you try latest version?

**Comment by liquidz** [comment]
Feel free to reopen if you have any problems :)
