### ISSUE TITLE
Skip prompts for GitHub username and password

### ISSUE THREAD

**Issue by CambodianCoder** [liquidz/antq#130]
I have several private repositories/packages hosted in Nexus listed in my deps.edn file. 

I would like to set a flag on the command line to skip checking for a username/password.

Something similar to the following would suffice:
```
clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version "RELEASE"}}}' -M -m antq.core --skip-authentication
```

Does this feature already exist? If not, could it be added?

Currently, I have to manually hit enter multiple times to get past all the password prompts.

![image](https://user-images.githubusercontent.com/35553625/146982033-fea54b30-955a-4b30-812b-cfe18f75e2f1.png)

**Comment by liquidz** [comment]
@CambodianCoder Thanks for your reporting!

Hmm, the cause may be the feature to show diffs between current and latest version. (Prompt from `git` command)
https://github.com/liquidz/antq/blob/de79d34bc4d951480f41cbb2e736cdc215a30d68/src/antq/diff/java.clj#L84-L89

For now, antq refers a `<url>` under `<project>` or  `<scm>` in pom.xml.
e.g.
- https://github.com/liquidz/antq/blob/de79d34bc4d951480f41cbb2e736cdc215a30d68/pom.xml#L9
- https://github.com/liquidz/antq/blob/de79d34bc4d951480f41cbb2e736cdc215a30d68/pom.xml#L16-L20

What is your `<url>` in pom.xml stored in Nexus?

I can add `--no-diff` option to skip cheking diffs, but it also skips diffs for public repositories, which doesn't seem to make sense.
