### ISSUE TITLE
Consider moving to `tools.build` for building

### ISSUE THREAD

**Issue by dharrigan** [liquidz/antq#143]
Hi,

Depstar by Sean Corfield is deprecated, and he encourages people to move to `tools.build`. I've done an initial bit of work around this on my branch. Worth considering? Happy to take feedback to make it work :-)

-=david=-

**Comment by liquidz** [comment]
@dharrigan Thanks for your suggestion.
But, unfortunately it's duplicated with #129, and I'm already working on it.

**Comment by dharrigan** [comment]
Hey! no worries at all! :-) Maybe it might of some use :-) Feel free to close this issue.

**Comment by liquidz** [comment]
Closed by #151
