### ISSUE TITLE
Progess bar?

### ISSUE THREAD

**Issue by vemv** [liquidz/antq#157]
Hi there,

for some really large projects, it can be pretty frustrating that antq doesn't show what it's doing.

So a progress bar would seem a nice addition, what do you think?

Cheers - V

**Comment by liquidz** [comment]
@vemv Yeah, it may be good as I knew I would need it someday :)

**Comment by pmonks** [comment]
[spinner](https://github.com/pmonks/spinner) may be of interest for this.  While the current release only supports indeterminate progress indicators ("spinners"), a community member (@Jungorend) has started looking into adding support for determinate progress indicators ("progress bars").

**Comment by liquidz** [comment]
@pmonks Interesting. Thanks!

**Comment by liquidz** [comment]
@vemv Sorry for late reaction.
I've added progress bar for `table` reporter.
https://github.com/liquidz/antq#--reporterreporter
Could you try [dev](https://github.com/liquidz/antq/tree/dev) branch?

https://user-images.githubusercontent.com/6941/171966159-14082044-c7bd-4fff-a6fb-584640e33964.mp4

**Comment by vemv** [comment]
Hey there! Thanks much for this feature.

It does look great from the video. I'll trust that it works correctly.

**Comment by liquidz** [comment]
@vemv Just released v1.8.847 #167
