### ISSUE TITLE
slf4j-simple dependency caused to crash

### ISSUE THREAD

**Issue by maxp** [liquidz/antq#16]
I have a line in deps.edn `org.slf4j/slf4j-simple  {:mvn/version "1.7.30"}` and got an exception.

 "Execution error (ClassCastException) at unilog.config/start-logging! (config.clj:354).\nclass org.slf4j.impl.SimpleLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.impl.SimpleLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app')\n",

{:clojure.error/class java.lang.ClassCastException,
  :clojure.error/line 354,
  :clojure.error/cause
  "class org.slf4j.impl.SimpleLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.impl.SimpleLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app')",
  :clojure.error/symbol unilog.config/start-logging!,
  :clojure.error/source "config.clj",
  :clojure.error/phase :execution}

**Comment by maxp** [comment]
Full stack trace
https://gist.github.com/maxp/4403dcb3a623b87b728f1adf89162af5

**Comment by maxp** [comment]
Looks like `unilog.config` strictly depends on lohback's Logger.
https://github.com/pyr/unilog/blob/master/src/unilog/config.clj#L339

**Comment by liquidz** [comment]
@maxp Sorry for late reply!
I'll have a look!

**Comment by liquidz** [comment]
@maxp I could reproduce the problem.
`unilog` is not mandatory, so I'll delete it from dependencies.

**Comment by liquidz** [comment]
@maxp I've cut a new release.
https://clojars.org/antq/versions/0.5.3
Could you try ver 0.5.3?

**Comment by maxp** [comment]
Works great!

**Comment by liquidz** [comment]
Thanks for your confirmation!

**Comment by liquidz** [comment]
Closed by #17
