### ISSUE TITLE
Progress bar is overwritten

### ISSUE THREAD

**Issue by dharrigan** [liquidz/antq#176]
Hi!

On some occasions, I see this:

`All dependencies are up-to-date.#################### ] 79/79`

After the dependencies have been updated. 

(If I was to make another little suggestion, is to remove the spaces after/before the `[]` so that it's like `[******]`, not `[ ****** ]`, as a gap suggests a skip, something missing if you know what I mean :-))

Thank you.

-=david=-

**Comment by liquidz** [comment]
@dharrigan Thanks for your reporting!
I've fixed, so could you try [dev](https://github.com/liquidz/antq/tree/dev) branch?

**Comment by dharrigan** [comment]
Hi,

Seems to work a-okay! ;-)

-=david=-

**Comment by liquidz** [comment]
Thanks for your confirmation!
Just released v1.9.874 :)
