### ISSUE TITLE
Request: Exit Code other than 0 on outdated dependencies

### ISSUE THREAD

**Issue by Wegi** [liquidz/antq#19]
Hi there,

thank you for this awesome tool.
Would it be possible to add a flag that activates an exit code other than 0, when any of the dependencies is outdated?
This would be useful in a CI, which automatically checks code for outdated dependencies.

**Comment by Wegi** [comment]
I took a look in the code and it should exert this behavior, but it does not currently.
An outdated dependency is found, but the exit code is still 0.
```
 echo $?
0
```

**Comment by Wegi** [comment]
I created a pull request, that should fix this behavior: https://github.com/liquidz/antq/pull/20

**Comment by liquidz** [comment]
@Wegi Thanks for your reporting!

Oh, that's a regression in 0.6.0.
0.5.3 returned `1` if there are outdated dependencies.
https://github.com/liquidz/antq/blob/0.5.3/src/antq/format.clj#L64

Great catch! Thanks a lot!

**Comment by liquidz** [comment]
@Wegi I've cut a new release :)

**Comment by Wegi** [comment]
Perfect, thank you!
