### ISSUE TITLE
Add support for `^:antq/ignore` for ignoring package

### ISSUE THREAD

**Issue by kimmoahola** [liquidz/antq#190]
Add support for ignoring the upgrade of a package directly in the package definition.

I think `^:ignore` or `^:antq/ignore` would be handy in package definition in deps.edn. I think it's good to mark 'ignore' directly to the package definition because easy to spot there when I have 30 packages in a project.

depot has that kind of meta to ignore stuff: https://github.com/Olical/depot#controlling-which-part-of-the-file-are-checked

Example snip from deps.edn:
```
hikari-cp/hikari-cp ^:antq/ignore {:mvn/version "2.14.0"} ;; Greater than 2.14.0 does not work with java 8.
```

**Comment by kimmoahola** [comment]
Yes that would be good for consistency!

**Comment by kimmoahola** [comment]
I confirm that it works great. Thank you for quick response!

**Comment by liquidz** [comment]
Thanks for your confirmation!
I'll add same support for leiningen, shadow-cljs, etc.

**Comment by liquidz** [comment]
@kimmoahola Just released v2.2.962 #191

**Comment by liquidz** [comment]
FYI https://github.com/liquidz/antq/blob/main/doc/exclusions.adoc

**Comment by kimmoahola** [comment]
Thank you! Tested it and it seems 🥇
