### ISSUE TITLE
minor inconsiquential source code typo: devleopment -> development

### ISSUE THREAD

**Issue by lread** [liquidz/antq#193]
I was wondering why antq was not reporting on the [latest pedestal release](https://clojars.org/io.pedestal/pedestal.log/versions/0.5.11-beta-1).
I discovered that antq does not report on `alpha` `beta` and `rc` releases.
Which seems very reasonable.

While reading antq source (which is very clean, @liquidz, a joy to read), I noticed a typo in a function name, hence this issue:
https://github.com/liquidz/antq/blob/74af1a33714b8e9fd5188b6374cec9d78a058b47/src/antq/ver.clj#L9-L15

I think you meant `under-development?` instead of `under-devleopment?`.
In inconsequential typo, but thought you'd appreciate the ping.

**Comment by liquidz** [comment]
@lread Oh, nice catch! Thanks for your reporting!
