### ISSUE TITLE
Lots of Timed out errors

### ISSUE THREAD

**Issue by seancorfield** [liquidz/antq#205]
I don't know whether something changed in one of the recent `antq` releases, but I'm seeing `Timed out` a lot more these days in the report it produces. Could `antq` perhaps retry more if it gets a timeout trying to fetch version information?

**Comment by liquidz** [comment]
@seancorfield Thank you for reporting!

Hmm, I'm not seeing `Timed out` message in my environment, and recent changes are only bumping libraries.
I'll check those library's changelogs more.

> Could antq perhaps retry more if it gets a timeout trying to fetch version information?

How about these environmental variables?
https://github.com/liquidz/antq/blob/main/doc/timeout.adoc

**Comment by seancorfield** [comment]
Since bumping the env var to 30s, I have seen no Timed out errors (my Windows/WSL2 setup occasionally "sleeps" on network access, hence the timeouts). Thank you!
