### ISSUE TITLE
Incorrect resolution of relative :local/root paths

### ISSUE THREAD

**Issue by danskarda** [liquidz/antq#207]
Imagine you have the directory structure similar to Polylith:

1. There is `projects/development/deps.edn`

```clojure
{:deps {component/foobar   {:local/root "../../components/foobar"}}}
```

2. and there is another `deps.edn` in `components/foobar` (relative too project root) 

3. you run antq from project root with parameters `:directory ["projects/development"]`

4. then antq fails to find `component/foobar` directory.

I did some debugging and found a place most likely responsible for the issue:

https://github.com/liquidz/antq/blob/9715ef8e30a6fd9b4179bc0ade7f5d8c1619e69b/src/antq/dep/clojure.clj#L83

Function `get-relative-path-by-current-working-directory` returns `projects/development/..components/foobar` and not `components/foobar` as expected.

I suspect the reason is custom concatenation of paths as strings. When I use `io/file` for standard filename concatenation, `(str (io/file dir relative-path))` works fine (under Linux, I do not know about platforms with \\ separators).

**Comment by liquidz** [comment]
@danskarda Thank you for your reporting!
I'll have a look tomorrow.

**Comment by liquidz** [comment]
@danskarda Thanks for your advice!
I just released [2.2.1017](https://github.com/liquidz/antq/releases/tag/2.2.1017).
Could you try the latest version?

**Comment by danskarda** [comment]
Hi @liquidz, I tested 2.2.1017 and it works in my project as expected. Thanks!

**Comment by liquidz** [comment]
Thanks for your confirmation!
