### ISSUE TITLE
shadow-cljs file containing #shadow/env or #env crashes antq

### ISSUE THREAD

**Issue by Wegi** [liquidz/antq#21]
Shadow-cljs supports the #shadow/env and #env reader litteral (see: https://shadow-cljs.github.io/docs/UsersGuide.html#shadow-env). Antq crashes with the following error if one of those is used in the shadow-cljs.edn:

```
Execution error at antq.dep.shadow/extract-deps (shadow.clj:18).
No reader function for tag env
```

**Comment by liquidz** [comment]
@Wegi Thanks for your reporting!
I'll fix it.

**Comment by liquidz** [comment]
NOTE: shadow-cljs has only `shadow/env` and `env` readers for config file currently.
https://github.com/thheller/shadow-cljs/blob/2.10.21/src/main/shadow/cljs/devtools/config.clj#L102-L107

**Comment by liquidz** [comment]
@Wegi I just cut a new release to fix this problem.
Could you try latest version?

**Comment by Wegi** [comment]
Its solved :+1: Thank you very much.
