### ISSUE TITLE
More useful output for dependencies with git/sha coordinates?

### ISSUE THREAD

**Issue by pmonks** [liquidz/antq#24]
When used on a `deps.edn` based project that uses git/sha coordinates to select a dependency, we see output like this: 
```
|    :file |                        :name | :version | :latest-version |
|----------+------------------------------+----------+-----------------|
| deps.edn |              athos/clj-check |          | Failed to fetch |
|          | noisesmith/lein-git-info-edn |          | Failed to fetch |
```

Are there plans afoot to check the latest version of dependencies expressed via git/sha coordinates?

I _believe_ this can be achieved using the [`git ls-remote` command](https://git-scm.com/docs/git-ls-remote.html).

**Comment by liquidz** [comment]
@pmonks I've had a plan to support, but it was a low priority.

Now I've found you who needs it, so I'll try to support :)

**Comment by liquidz** [comment]
@pmonks I tried to support in `dev` branch.
Could you try?

* checkout `dev` branch
* run `make uberjar` to generate `target/antq-standalone.jar`
* run `java -jar /path/to/your/antq/repo/target/antq-standalone.jar` in your project directory

**Comment by pmonks** [comment]
Awesome! Should be able to check it out over the weekend.

**Comment by pmonks** [comment]
👍 LGTM! 👍

I tested it with both out-of-date and current git/sha coordinates, and it correctly handled both.  Note that both of these dependencies were for public repositories - I don't currently have any easy way to test the fix against a private git/sha coordinate.

**Comment by liquidz** [comment]
@pmonks Thanks for your confirmation!

I created a secret repo and tested as following.
* deps.edn
```
{:paths ["src"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        liquidz/secrettest {:git/url "git@github.com:liquidz/****.git"
                            :sha "****"}}}
```
* confirm that `clj` works well
  * c.f. https://www.clojure.org/reference/deps_and_cli#_git
* confirm that antq can resolve HEAD

It seems good to me too 👍

**Comment by liquidz** [comment]
I've cut a new release ☺️  #25

**Comment by pmonks** [comment]
Awesome! Thanks for addressing this so quickly!
