### ISSUE TITLE
Upgrade is not working when dependency version is destructed.

### ISSUE THREAD

**Issue by Kaspazza** [liquidz/antq#241]
Running upgrade on deps.edn will always tell which versions to update, but will not follow through if the version is saved as:
#:mvn{:version "x.x"}
And will work correctly if the dependency is written in fully qualified keyword like:
{:mvn/version "x.x"}

**Comment by liquidz** [comment]
@Kaspazza Thanks for your reporting!
Ah, I missed it. I'll fix!

**Comment by liquidz** [comment]
@Kaspazza I've fixed in [bugfix/upgrade-with-destructed](https://github.com/liquidz/antq/tree/bugfix/upgrade-with-destructed) branch.
Could you try?

**Comment by Kaspazza** [comment]
@liquidz  Hi, sorry for not responding earlier, I didn't notice the message.

Yeah, it works, but it asks twice about the same dependencies (both with destructured or not)

I run it with code, requiring  [antq.core] 
(antq.core/-main --upgrade --directory=/absolute/path/to/my/repo --exclude lib --exclude lib2 --exclude lib3)

**Comment by liquidz** [comment]
Hmm, I'll have a look.

**Comment by liquidz** [comment]
@Kaspazza Sorry, I've been unwell.

> Yeah, it works, but it asks twice about the same dependencies (both with destructured or not)

Thanks for your reporting! This was another bug and I've fixed in the same branch.
Could you try [bugfix/upgrade-with-destructed](https://github.com/liquidz/antq/tree/bugfix/upgrade-with-destructed) branch again?

**Comment by liquidz** [comment]
@Kaspazza Just released v2.8.1165 :)

**Comment by Kaspazza** [comment]
@liquidz Great, thanks!
