### ISSUE TITLE
-X/-T usage affected by System/exit

### ISSUE THREAD

**Issue by seancorfield** [liquidz/antq#261]
When used as a tool (-X/-T usage), the expected "exit" behavior is to just return a value or throw an exception, rather than calling `System/exit`.

I suspect this is why the following does not work properly on Clojure 1.12.0:

```clojure
user=> (invoke-tool {:debug true :preserve-envelope true :tool-name "antq" :fn 'outdated :args {:clojure.exec/out :capture}})
args [outdated #:clojure.exec{:out :capture, :invoke :fn}]
Invoking:  clojure -Tantq -
Execution error (ExceptionInfo) at clojure.tools.deps.interop/invoke-tool (interop.clj:83).
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

What _should_ happen here is that the execution "envelope" containing stdout should be returned, but instead no envelope is captured and the presence of stderr output (from SLF4J) leads `invoke-tool` to assume the tool has failed.

I believe that if `antq` returned a value (even `nil`) for successful tool execution, or threw an exception for unsuccessful tool execution, then it would work correctly with 1.12's `invoke-tool` function.

**Comment by liquidz** [comment]
@seancorfield Thanks for your reporting! I'll have a look.

**Comment by liquidz** [comment]
@seancorfield I've fixed in [fix-261](https://github.com/liquidz/antq/tree/fix-261) branch.
Coud you try?

**Comment by seancorfield** [comment]
That certainly seems to fix the installed tool usage, yes! Thank you!

**Comment by liquidz** [comment]
@seancorfield Thanks for your confirmation!

**Comment by liquidz** [comment]
@seancorfield Just released v2.9.1232 :)

**Comment by dpassen** [comment]
This broke running via '-X'
```sh
$ clj -X:antq
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[##################################################] 7/7
| :file    | :name               | :current | :latest |
|----------+---------------------+----------+---------|
| deps.edn | org.clojure/clojure | 1.11.4   | 1.12.0  |

Available changes:
- https://github.com/clojure/clojure/blob/clojure-1.12.0/changes.md
Execution error (ExceptionInfo) at antq.tool/outdated$fn (tool.clj:56).
Exited

Full report at:
/var/folders/l2/4c_1v4jj7kj9sfhwjmplz2s80000gn/T/clojure-14409212056517983648.edn
```

with the alias defined as:
```cld
:antq
{:extra-deps
 {io.github.liquidz/antq
  {:git/tag "2.9.1232"
   :git/sha "c1d0f9e"}}
 :exec-fn antq.tool/outdated}
```

**Comment by seancorfield** [comment]
I'll argue that's not broken: that's the behavior it _should_ have with with `-X` for "failed run" -- throw an exception. That's idiomatic.

You could definitely argue for a new option that doesn't treat outdated deps as an error.

Or you can use `-M -m` and rely on the exit status.

**Comment by seancorfield** [comment]
(as an example, see Cognitect's own test-runner when run with `-X` it throws an exception if any tests fail; with `-M -m` it exits with a non-zero status instead)

**Comment by frou** [comment]
`clojure -Tantq outdated` exiting with status 1 is completely understandable, but `Execution error` and the last few lines of the output pointing at a file with a stack trace is goofy. The majority of users (incl. me) are probably going to think that means the tool is broken and it's time to file a bug report.

**Comment by seancorfield** [comment]
The README should be updated to clarify the error case -- but this is how `-X` / `-T` tooling is generally supposed to work, so that it interops properly with `build.clj` stuff and Clojure 1.12's `invoke-tool`. The `Execution error` and stack trace is coming from the Clojure CLI in this case but would be programmatic in those other cases and you would `try`/`catch` in your code.
