### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by maxp** [liquidz/antq#29]
Annoying message appears at start
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Adding `org.slf4j/slf4j-nop {:mvn/version "RELEASE"}}` to deps solves the problem, but it is not mentioned in README.

**Comment by liquidz** [comment]
@maxp Thanks!
I'll update README

**Comment by liquidz** [comment]
Closed by #30
