### ISSUE TITLE
feature request: upgrade the deps like `lein ancient upgrade` ?

### ISSUE THREAD

**Issue by lucywang000** [liquidz/antq#36]
I've been using [lein-ancient](https://github.com/xsc/lein-ancient) to upgrade deps in project.clj, but it obviously only supports lein, and I really miss such a tool for detecting outdated deps in shadow-cljs.edn until I find antq.

But antq seems to only able to list the outdated deps, and not able to update it automatically. 

Is it feasible to implement this functionality, e.g using the [rewrite-edn](https://github.com/borkdude/rewrite-edn) library?

**Comment by liquidz** [comment]
@lucywang000 Thanks for your suggestion!

I have a plan to support the feature, but I haven't started yet. (PR is very welcomed)

antq supports also YAML(GitHub Actions) and XML(pom.xml), so it may needed some other libraries too.
It's hard to deal with them all from the start, so I'll deal with them in stages.

**Comment by liquidz** [comment]
@lucywang000 I just added `--upgrade` option to antq v0.9.0 by #40 
Currently upgrading YAML(GitHub Actions) is not supported yet, but other formats are supported!

Any problems, feel free to reopen this issue :)
