### ISSUE TITLE
Doesn't appear to work correctly in the presence of -RC versions

### ISSUE THREAD

**Issue by pmonks** [liquidz/antq#47]
I have some code that was depending on a release candidate of a published open source library, specifically `org.suskalo/discljord {:mvn/version "1.2.0-RC1"}`.  As can be seen, this version string follows the standard Maven representation of a release candidate, by using a "-RC#" suffix.

Today the developer of this library announced that the GA version of v1.2.0 had been released, with the following coordinate: `org.suskalo/discljord {:mvn/version "1.2.0"}`.  Again this is a bog-standard Maven version.

antq v0.9.3 did not detect that the newer version was available however - it simply stated "All dependencies are up-to-date.".

**Comment by liquidz** [comment]
@pmonks Thanks for your reporting!

It may be version comparing problem.
https://github.com/liquidz/antq/blob/0.9.3/src/antq/ver/java.clj#L72

I'll have a look.

**Comment by liquidz** [comment]
@pmonks I couldn't reproduce the problem.

```console
$ cat deps.edn
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.10.1"}
  org.suskalo/discljord {:mvn/version "1.2.0-RC1"}}

 :aliases
 {:outdated
  {:extra-deps {antq/antq {:mvn/version "0.9.3"}}
   :main-opts ["-m" "antq.core"]}}}

$ clojure -M:outdated
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

|    :file |                 :name |  :version | :latest-version |
|----------+-----------------------+-----------+-----------------|
| deps.edn | org.suskalo/discljord | 1.2.0-RC1 |           1.2.0 |
```

Could you tell me minimum steps to reproduce?

**Comment by pmonks** [comment]
Yep that's pretty much exactly what I've got here (albeit with more dependencies than just `org.suskalo/discljord`).

Might it have been a (temporary) caching issue?  `org.suskalo/discljord "1.2.0"` was only published today and I was checking within 30 minutes or so of it being deployed, so if antq uses any kind of local Maven metadata, or relies on a Maven artifact repository (Clojars, in this case) to report up-to-date metadata, that may explain what I observed.

**Comment by liquidz** [comment]
> Might it have been a (temporary) caching issue?

Maybe so.

antq depends on [maven-resolver-api](https://maven.apache.org/resolver/index.html) through [tools.deps.alpha](https://github.com/clojure/tools.deps.alpha).
https://github.com/liquidz/antq/blob/0.9.3/src/antq/ver/java.clj#L51-L66

Fetched versions also depends on this library, so I don't understand exactly where this library is using caches.

**Comment by pmonks** [comment]
Ok no worries.  I do know that caching (and things like derived index files that may lag actual library publication) is part of the Maven experience, so I'll just chalk it up to that and close the issue.

Oh and thanks again for `antq` - it's bloody great!
