### ISSUE TITLE
Upgrade does not honour `replace-deps` when upgrading dependencies.

### ISSUE THREAD

**Issue by dharrigan** [liquidz/antq#51]
If an alias uses this

```
           :uberjar {:replace-deps {seancorfield/depstar {:mvn/version "2.0.161"}}
                     :jvm-opts ["-Dclojure.compiler.direct-linking=true"]
                     :exec-fn hf.depstar/uberjar
                     :exec-args {:jar foo.jar
                                 :group-id foo
                                 :artifact-id bar
                                 :version "0.0.1"
                                 :main-class foo.bar.main
                                 :aot true
                                 :sync-pom true}}}
```

And `antq` is run like this:

```
❯ clj -M:antq

|    :file |                :name | :version | :latest-version |
|----------+----------------------+----------+-----------------|
| deps.edn |       metosin/reitit |   0.5.10 |          0.5.11 |
|          | seancorfield/depstar |  2.0.161 |         2.0.165 |
Upgraded seancorfield/depstar '2.0.161' to '2.0.165' in deps.edn.
Upgraded metosin/reitit '0.5.10' to '0.5.11' in deps.edn.
```

Notice that the `depstar` has apparently been upgraded to `2.0.165`, yet upon cat'ing the `deps.edn` file the version is still `2.0.161`. 

Changing `replace-deps` to `extra-deps` causes the `deps.edn` file have the dependency version successfully changed to `2.0.165`, therefore it appears that the upgrade doesn't know how to handle the `replace-deps` key.

**Comment by liquidz** [comment]
@dharrigan Thanks for your reporting!
I fixed in `dev` branch, so could you try following steps?

- pull `dev` branch
- run `make uberjar` to generate target/antq-standalone.jar
- run `java -jar /path/to/your/antq/repo/target/antq-standalone.jar` in your project directory

**Comment by dharrigan** [comment]
Confirmed fixed. Thank you :-)

**Comment by liquidz** [comment]
I just cut a new release #52
