### ISSUE TITLE
Cannot update dependencies in a password protected maven repo.

### ISSUE THREAD

**Issue by carrete** [liquidz/antq#54]
I'm using Datomic dev-local, https://docs.datomic.com/cloud/dev-local.html, which uses a password protected maven repo.

I have a ~/.m2/settings.xml that includes:
```xml
    <server>
       <id>cognitect-dev-tools</id>
       <username>${env.COGNITECT_DEV_TOOLS_USERNAME}</username>
       <password>${env.COGNITECT_DEV_TOOLS_PASSWORD}</password>
    </server>
```

a pom.xml that includes:
```xml
    <repository>
      <id>cognitect-dev-tools</id>
      <url>https://dev-tools.cognitect.com/maven/releases/</url>
    </repository>
```

and a deps.edn that looks like:
```clojure
{:mvn/repos {"cognitect-dev-tools" {:url "https://dev-tools.cognitect.com/maven/releases/"}}
 :deps {com.datomic/dev-local {:mvn/version "0.9.225"}
        ...}
 ...}
 ```
 
Everything works with tools.deps. Only antq appears to have a problem. For example:
```
|    :file |                 :name | :version | :latest-version |
|----------+-----------------------+----------+-----------------|
| deps.edn | com.datomic/dev-local |  0.9.225 | Failed to fetch |
|  pom.xml | com.datomic/dev-local |  0.9.225 | Failed to fetch |
```

One possible theory is that this is because "antq is using tools.deps.alpha for parts of its maven code, but not using it to read deps from deps.edn files" (hat tip Alex Miller).

**Comment by liquidz** [comment]
@carrete Thanks for your reporting!
I'll have a look.

**Comment by liquidz** [comment]
maven-metadata.xml for `com.datomic/dev-local` may not be provided?
https://dev-tools.cognitect.com/maven/releases/com/datomic/dev-local/maven-metadata.xml

**Comment by carrete** [comment]
> maven-metadata.xml for com.datomic/dev-local may not be provided?

I'll ask on the #datomic channel in Clojurians on Slack.

**Comment by puredanger** [comment]
s3 repos typically do not provide maven-metadata.xml and LATEST won’t work on them.

**Comment by carrete** [comment]
Thanks @puredanger. @liquidz, feel free to close this issue

**Comment by liquidz** [comment]
@carrete Thanks for confirmation!
BTW, I used [sonatype/nexus3](https://hub.docker.com/r/sonatype/nexus3) to confirm password protected maven repo can be checked by antq, and it works well 😄

**Comment by carrete** [comment]
> I used [sonatype/nexus3](https://hub.docker.com/r/sonatype/nexus3) to confirm password protected maven repo can be checked by antq, and it works well 😄 

I shouldn't have assumed it was a password related issue. ☹️ If you'd like @liquidz, I'd be happy to submit a pull-request to update the README with a note about S3 repos.

**Comment by liquidz** [comment]
@carrete pull-request is very welcomed ☺️

**Comment by liquidz** [comment]
@carrete BTW S3 repo in my company has `maven-metadata.xml`, so I don't necessarily think `maven-metadata.xml` doesn't exist in S3 repo.

**Comment by puredanger** [comment]
It depends entirely on how the jars get put in the s3 repo. Many people just upload jar/Pom to a bucket and then you won’t have it. If the upload process creates or uploads a metadata file, then it will.

**Comment by carrete** [comment]
Thanks @puredanger
