### ISSUE TITLE
Consider supporting blacklisting a specific dependency version

### ISSUE THREAD

**Issue by lread** [liquidz/antq#75]
Still loving antq, thanks @liquidz!

Scenario: I am using antq to check for outdated dependencies. I reports that there is a new version v of dependency d.  I discover though that there is a serious enough bug in dependency d version v that'd I do not want to upgrade. 

Ideally I'd like to tell antq to no longer tell me about dependency d version v being available. I'm just not interested.
I am, though, interested in learning about the next version v of dependency d when it becomes available.

Not sure what form this exclusion config would take, thought I'd first check if the idea might be of interest.

**Comment by liquidz** [comment]
@lread Thanks for your suggestion!

> Not sure what form this exclusion config would take, thought I'd first check if the idea might be of interest.

Indeed.
Sometimes I'd like to ignore specific version.
The feature will help me too :)

We have already [--exclude](https://github.com/liquidz/antq#--excludeartifact_name) option to ignore specific dependency, so for example, we can extend this option to be able to specify version like `--excude=d@v`.
(I believe the `dep@version` format is common because it is used by `npm`, `brew`, etc)

**Comment by lread** [comment]
Yeah, I think that'd work well @liquidz.  I currently only see need to blacklist one version, I think(?).

Here's a nuance: Let's say I am at version 1.1.0 of lib x and the current release version is 1.1.2. I know I don't want 1.1.2, so I exclude x@1.1.2.  If there is a v1.1.1 also available, would antq recommend v1.1.1?  Or I am I really excluding v1.1.2 and all version before it?

**Comment by liquidz** [comment]
@lread 
> Here's a nuance: Let's say I am at version 1.1.0 of lib x and the current release version is 1.1.2. I know I don't want 1.1.2, so I exclude x@1.1.2. If there is a v1.1.1 also available, would antq recommend v1.1.1? Or I am I really excluding v1.1.2 and all version before it?

It seems intuitive that `x@1.1.2` excludes only v1.1.2.
So v1.1.1 should be reported as available. (because v1.1.0 is outdated)

antq has a version list internally, and it shouldn't be too hard.

**Comment by lread** [comment]
Sounds good! So if we were wanting to exclude multiple versions of lib x, I would simply specify both `--exclude=x@1.1.1` and `--exclude@1.1.2`

**Comment by liquidz** [comment]
@lread I've not tested enough yet, but I've tried to add the feature in `dev` branch.

**Comment by liquidz** [comment]
Just released v0.14.0 #76 
Feel free to reopen it you have any problems :)
