### ISSUE TITLE
Support :git/tag and :git/sha for deps.edn

### ISSUE THREAD

**Issue by liquidz** [liquidz/antq#93]
c.f. https://clojure.org/reference/deps_and_cli#_dependencies

**Comment by pmonks** [comment]
Yes please!  I switched over from `:sha` to `:git/sha` in my projects, and now antq won't check those dependencies.  😢

**Comment by liquidz** [comment]
@pmonks Sorry for the late work, I've been working on another project.

I just cut a new release, so could you try the latest version? #110

**Comment by dpassen** [comment]
This new build seems to support :git/sha but not :git/tag. Is that correct?

**Comment by liquidz** [comment]
@dpassen Correct.
We can't use `:tag` or `:git/tag` without `:sha` or `:git/sha`, so antq wasn't aware of `:tag` originally.

**Comment by pmonks** [comment]
No need to apologise - you're putting out high quality open source and can and should work at whatever pace works for you!

Oh and v1.0.1 works great - thank you!

**Comment by liquidz** [comment]
@dpassen Ah, we should handle `:tag` and `:git/tag` when upgrading deps.edn. I forgot about that.

I'll fix it this weekend.

**Comment by dpassen** [comment]
I can help, possibly, if desired.

**Comment by liquidz** [comment]
@dpassen Thanks! PR is very welcomed!

But I'm working on deps.edn upgrader for a bug fix now, so it's best not to start fixing it yet to avoid conflicts.

**Comment by liquidz** [comment]
Just released for a bugfix #112 
I'll continue to implement upgrading `:git/tag`

**Comment by liquidz** [comment]
Just cut a new release which supports upgrading `:tag` and `:git/tag` #114 
cc @dpassen
