### ISSUE TITLE
Support inferring :git/url

### ISSUE THREAD

**Issue by liquidz** [liquidz/antq#94]
c.f. https://clojure.org/reference/deps_and_cli#_dependencies
c.f. https://github.com/clojure/tools.deps.alpha/blob/1c008c491524bd21b16a39e94a3bf592886fae23/src/main/clojure/clojure/tools/deps/alpha/extensions/git.clj#L23-L33

**Comment by seancorfield** [comment]
I just submitted a PR for this #106 (as I just ran into it myself). Oh, just noticed t.d.a supports bitbucket and beanstalk too -- let me update the PR!

**Comment by liquidz** [comment]
@seancorfield Thanks for your great work!

I've jut cut a new release #107

**Comment by seancorfield** [comment]
Thanks! I have updated my dot-clojure file to use that and just ran it across all my projects :)
